// Array of random controversial but important questions about God
const controversialQuestions = [
    "If God is all-powerful, why does evil exist in the world?",
    "Does God predetermine our fates, or do we have free will?",
    "Is it fair for God to punish people for sins they were born inclined to commit?",
    "Why would an all-loving God allow eternal suffering in hell?",
    "Can God be proven to exist through science, or is faith the only way?",
    "If God created the universe, who or what created God?",
    "Does God favor one religion over others, or are all paths to Him equal?",
    "Why does God remain silent in the face of human suffering?",
    "Is God responsible for natural disasters, or are they purely random?",
    "Can a just God forgive atrocities like genocide without punishment?",
    "Does God’s omniscience mean He knows our every sin before we commit it?",
    "Why would God create humans only to test them with temptation?",
    "Is the concept of God a human invention to explain the unknown?",
    "If God is perfect, why is the world He created so flawed?",
    "Does God intervene in human affairs, or has He abandoned us?",
    "Why would an all-knowing God create beings capable of defying Him?",
    "If God is infinite, why does He demand finite beings worship Him?",
    "Does God’s justice conflict with His mercy in judging humanity?",
    "Why does God allow children to suffer if He loves all equally?",
    "Is God’s existence compatible with the vastness of an indifferent universe?",
    "If God is unchanging, why do His commandments evolve over time?",
    "Does God’s love extend to those who reject Him entirely?",
    "Why would God create a world where His presence must be questioned?",
    "Is God bound by logic, or can He defy it to perform miracles?",
    "If God knows the future, why does He allow prayers to go unanswered?",
    "Does God’s omnipotence mean He could end all suffering but chooses not to?",
    "Why does God permit religious wars fought in His name?",
    "Is God’s will truly benevolent if it includes pain and loss?",
    "Can God judge fairly if He created us with differing capacities for faith?",
    "If God is everywhere, why do so many feel abandoned by Him?",
    "Does God’s eternity mean He experiences time differently than we do?",
    "Why would God create a universe so vast yet focus on one tiny planet?",
    "If God is all-good, how can He allow the existence of a devil?",
    "Does God’s plan include suffering as a necessary path to redemption?",
    "Why does God demand faith when evidence could unite humanity?",
    "Is God’s omnipresence a comfort or an intrusion into human privacy?",
    "If God is beyond comprehension, why do scriptures claim to define Him?",
    "Can God’s love be unconditional if salvation depends on belief?",
    "Why does God allow the innocent to bear the consequences of others’ sins?",
    "Does God’s creation of death contradict His role as a life-giver?",
    "If God is sovereign, why does He permit chaos to reign in the world?",
    "Why would God create beauty only to let it be destroyed by suffering?",
    "Is God’s silence a test of faith or a sign of indifference?",
    "Does God’s power diminish if humans can thwart His will?",
    "If God values humility, why does He demand praise and glory?",
    "Why does God allow conflicting revelations to divide His followers?",
    "Can God truly forgive if His forgiveness requires repentance?",
    "If God designed free will, is He accountable for its misuse?",
    "Does God’s perfection mean He cannot relate to human imperfection?",
    "Why would God create a world where His existence is debated?",
    "Is God’s wrath a sign of justice or a flaw in His character?",
    "If God is timeless, why does He act within human history?",
    "Does God’s creation of diversity conflict with His call for unity?",
    "Why does God allow faith to falter in the face of modern science?",
    "Can God be all-powerful if He cannot sin or be tempted?",
    "If God knows all outcomes, why does He allow us to choose wrongly?",
    "Does God’s love for humanity extend to those who never hear of Him?",
    "Why would God create a soul only to risk its eternal damnation?",
    "Is God’s omnipotence limited by the laws of nature He established?",
    "If God is spirit, why does He care about physical obedience?",
    "Does God’s promise of heaven justify the suffering on earth?",
    "Why does God allow His name to be used to justify violence?",
    "Can God’s goodness coexist with the randomness of tragedy?",
    "If God is the source of morality, why do His followers disagree on right and wrong?",
    "Does God’s creation of life imply He owes us purpose?",
    "Why would God hide His presence from those who seek Him earnestly?",
    "Is God’s judgment eternal, or can it be reversed in the afterlife?",
    "If God controls destiny, why does prayer influence His will?",
    "Does God’s omniscience make human effort ultimately meaningless?",
    "Why does God allow doubt to overshadow faith in His existence?",
    "Can God be truly compassionate if He permits unending grief?",
    "If God is the author of all, why does He allow evil to persist?",
    "Does God’s transcendence mean He’s detached from human pain?",
    "Why would God create a universe where His love is questioned?",
    "Is God’s sovereignty undermined by the existence of chance?",
    "If God values truth, why does He allow deception in His name?",
    "Does God’s creation of hell reflect justice or cruelty?",
    "Why does God demand loyalty when His actions seem inconsistent?",
    "Can God’s will be perfect if it includes human rebellion?",
    "If God is light, why does darkness prevail in His world?",
    "Does God’s eternity make human suffering insignificant to Him?",
    "Why would God create a world where His justice seems delayed?",
    "Is God’s omnipotence compromised by His inability to be unjust?",
    "If God is peace, why does He allow turmoil among His believers?",
    "Does God’s love require sacrifice, or is it freely given?",
    "Why does God permit the faithful to endure the worst trials?",
    "Can God’s existence be reconciled with a universe that seems godless?",
    "If God is the beginning, why does He allow endings filled with pain?",
    "Does God’s omniscience mean He foresaw every betrayal against Him?",
    "Why would God create a cosmos where His voice is barely a whisper?",
    "Is God’s plan for humanity a mystery by design or by neglect?",
    "If God is infinite, why does He limit His revelations to a few?",
    "Does God’s justice demand suffering, or is it a human misinterpretation?",
    "Why does God allow His creation to question His very existence?",
    "Can God’s mercy extend to those who curse Him until their last breath?",
    "If God is all-sufficient, why does He seek a relationship with us?",
    "Does God’s creation of time mean He’s bound by its consequences?",
    "Why would God craft a world where His presence feels optional?",
  ];
  
  export default controversialQuestions;